name: Node.js Auto CI

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      moduleDir: ${{ steps.auto-ci.outputs.moduleDir}}
      info: ${{ steps.auto-ci.outputs.info}}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - uses: actions/checkout@v2
      - name: auto-ci
        id: auto-ci
        uses: wangziling100/AutoCI@v1.0.8
        with:
          configPath: .github/autoCI.config.json
          #modulesDir: packages
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY }}
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{steps.auto-ci.outputs.moduleDir}}/dist